#!/usr/bin/env python3
"""chaotic-tier-audit — pre-assign nog tiers to chaotic-aur packages.

KognogOS ships chaotic-aur enabled (Javier's ruling, 2026-07-30): packages
are governed by nog's tier system anyway, so the repo's risk surface is
managed by *classification*, not exclusion. This script audits the live
chaotic-aur package list and generates the Tier 1 pre-assignments for the
factory tier-pins.toml, spliced between BEGIN/END markers so it can be
regenerated every annual release.

Classification rules (ordered):
  Tier 1 — a bad update can brick the machine:
    * real kernels (linux-*, minus known apps; -headers excluded because
      nog auto-couples <X>-headers to <X>'s tier)
    * firmware variants (linux-firmware-*) — matches factory linux-firmware
    * graphics stacks: mesa*-git, nvidia legacy branches (nvidia-NNNxx*)
    * libc replacements (glibc-*)
    * the package manager itself (pacman-git)
    * filesystem kernel modules (zfs-*)
    * boot-entry writers (limine-*, refind-*)
  Fail-safe: an UNRECOGNIZED linux-* package classifies Tier 1 and is
  printed for review — over-holding an app is harmless, under-holding a
  kernel is not.
  Everything else needs no pin: Tier 3 (7-day hold) is nog's default.

Usage:
  scripts/chaotic-tier-audit.py            # print the generated block
  scripts/chaotic-tier-audit.py --write    # splice into config/tier-pins.toml

Requires chaotic-aur enabled in pacman.conf (it reads `pacman -Sl`).
"""

import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
TIER_PINS = REPO_ROOT / "config" / "tier-pins.toml"

BEGIN = "    # BEGIN CHAOTIC-TIER1 (generated by scripts/chaotic-tier-audit.py)"
END = "    # END CHAOTIC-TIER1"

# linux-* packages that are applications, not kernels.
LINUX_APPS = {
    "linux-wifi-hotspot",
    "linuxtv-dvb-apps",
}

TIER1_PATTERNS = [
    # (rule name, regex)
    ("firmware", re.compile(r"^linux-firmware")),
    ("kernel", re.compile(r"^linux")),
    ("mesa-git", re.compile(r"^mesa\S*-git$")),
    ("nvidia-legacy", re.compile(r"^nvidia-\d+xx")),
    ("libc", re.compile(r"^glibc-")),
    ("pacman", re.compile(r"^pacman-git$")),
    ("zfs", re.compile(r"^zfs-")),
    ("boot-writer", re.compile(r"^(limine-|refind-)")),
]


def chaotic_packages():
    out = subprocess.run(
        ["pacman", "-Sl", "chaotic-aur"],
        capture_output=True, text=True,
    )
    if out.returncode != 0:
        sys.exit("chaotic-tier-audit: `pacman -Sl chaotic-aur` failed — "
                 "is chaotic-aur enabled in pacman.conf?")
    return [line.split()[1] for line in out.stdout.splitlines() if line.split()]


# Kernel package names an exact-version dependency can point at. A package
# that hard-depends on `<kernel>=<version>` is an out-of-tree kernel module:
# it version-locks to a Tier 1 kernel, so it must hold in lockstep or the
# split ignore list aborts the whole transaction (the 2026-07-30 dep-chain
# audit found dahdi-linux-git and wanpipe doing exactly this).
KERNEL_NAMES = re.compile(
    r"^linux(-lts|-zen|-hardened|-rt|-rt-lts)?$"
)


def kernel_module_packages():
    """Packages in chaotic-aur with an exact-version dep on a kernel."""
    out = subprocess.run(
        ["bsdtar", "-xOf", "/var/lib/pacman/sync/chaotic-aur.db"],
        capture_output=True, text=True, errors="replace",
    )
    if out.returncode != 0:
        print("chaotic-tier-audit: warning — could not read chaotic-aur.db; "
              "skipping the kernel-module dependency rule", file=sys.stderr)
        return set()
    found, name, field = set(), None, None
    for line in out.stdout.splitlines():
        line = line.strip()
        if line.startswith("%") and line.endswith("%"):
            field = line
        elif not line:
            field = None
        elif field == "%NAME%":
            name = line
        elif field == "%DEPENDS%" and "=" in line and name:
            dep = line.split("=", 1)[0]
            if KERNEL_NAMES.match(dep):
                found.add(name)
    return found


def classify(packages):
    """Return {rule: [pkg, ...]} for Tier 1, plus review notes."""
    tier1, notes = {}, []
    kmods = kernel_module_packages()
    for pkg in packages:
        if pkg in kmods:
            tier1.setdefault("kernel-module", []).append(pkg)
            continue
        if pkg in LINUX_APPS:
            continue
        if pkg.endswith("-headers"):
            continue  # nog auto-couples <X>-headers to <X>'s tier
        # lib32-<X> auto-couples to <X> in nog; skip explicit lib32 pins,
        # but only when the base package is itself present and classified.
        base = pkg.removeprefix("lib32-")
        matched = None
        for rule, rx in TIER1_PATTERNS:
            if rx.match(base):
                matched = rule
                break
        if matched is None:
            continue
        if pkg.startswith("lib32-") and base in packages:
            continue  # coupled to its base pin
        tier1.setdefault(matched, []).append(pkg)
        # Fail-safe visibility: kernels we have never reviewed by name.
        if matched == "kernel" and not KNOWN_KERNEL_FAMILIES.match(base):
            notes.append(f"NEW unreviewed linux-* package (pinned Tier 1): {pkg}")
    return tier1, notes


# Families reviewed by hand on 2026-07-30. A linux-* match outside these
# still pins Tier 1 (fail-safe) but gets flagged for human review.
KNOWN_KERNEL_FAMILIES = re.compile(
    r"^linux("
    r"-cachyos(-bore|-lts|-rc)?"
    r"|-cjktty|-lqx|-mainline|-nitrous|-tachyon"
    r"|-lts\d+"
    r"|-vfio(-lts|-x64v\d)?"
    r"|-x64v\d"
    r"|-xanmod(-edge)?(-lts|-rt)?(-x64v\d)?"
    r"|-znver\d"
    r"|-firmware\S*"
    r")$"
)


def render_block(tier1):
    lines = [BEGIN]
    lines.append("    # chaotic-aur is enabled by default in KognogOS; its packages are")
    lines.append("    # governed by the tier system like any other repo (everything not")
    lines.append("    # pinned here rides Tier 3's 7-day hold). Do not hand-edit this")
    lines.append("    # block — rerun the audit script and commit the diff.")
    rule_titles = {
        "kernel-module": "Out-of-tree kernel modules (exact-version dep on a Tier 1 kernel)",
        "kernel": "Chaotic kernels (-headers auto-couple)",
        "firmware": "Chaotic firmware variants",
        "mesa-git": "Chaotic mesa builds (lib32 auto-couples)",
        "nvidia-legacy": "Chaotic nvidia legacy branches",
        "libc": "Chaotic libc replacements",
        "pacman": "Chaotic package-manager builds",
        "zfs": "ZFS kernel modules + lockstep tools",
        "boot-writer": "Boot-entry writers",
    }
    for rule in ["kernel-module"] + [r for r, _ in TIER1_PATTERNS]:
        pkgs = sorted(tier1.get(rule, []))
        if not pkgs:
            continue
        lines.append(f"    # {rule_titles[rule]}")
        for pkg in pkgs:
            lines.append(f'    "{pkg}",')
    lines.append(END)
    return "\n".join(lines)


def splice(block):
    text = TIER_PINS.read_text()
    if BEGIN in text:
        pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
        new = pattern.sub(block, text)
    else:
        # First run: insert before the closing bracket of [tier1] packages.
        anchor = '    "nvidia-utils", "lib32-nvidia-utils",\n]'
        if anchor not in text:
            sys.exit("chaotic-tier-audit: could not find the [tier1] packages "
                     "anchor in tier-pins.toml — insert markers manually once.")
        new = text.replace(anchor, anchor[:-1] + "\n" + block + "\n]")
    TIER_PINS.write_text(new)


def main():
    write = "--write" in sys.argv
    packages = chaotic_packages()
    tier1, notes = classify(packages)
    block = render_block(tier1)
    total = sum(len(v) for v in tier1.values())
    print(block)
    print(f"\n# {total} Tier 1 pre-assignments from {len(packages)} "
          f"chaotic-aur packages", file=sys.stderr)
    for note in notes:
        print(f"# ⚠ {note}", file=sys.stderr)
    if write:
        splice(block)
        print(f"# spliced into {TIER_PINS}", file=sys.stderr)


if __name__ == "__main__":
    main()
